appiumConfig:
#  app: ""
  url: http://127.0.0.1:4723/wd/hub
  wait: 6
  capabilities:
    platformName: android
    deviceName: 192.168.56.101:5555
    appPackage: cn.futu.trader
    appActivity: cn.futu.app.main.activity.MainActivity
    unicodeKeyboard: true
    resetKeyboard: true
    noReset: true